### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by ydgkkang** [passionui/support#1]
+ watchman@1.0.0
added 1 package and audited 951639 packages in 18.917s

4 packages are looking for funding.
Run "npm fund" to find out more.
PS E:\front\source> npm start

> listar@1.0.0 start E:\front\source
> react-native start

error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (E:\front\source\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (E:\front\source\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:66:59)
    at getDefaultConfig (E:\front\source\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:82:20)
    at load (E:\front\source\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:118:25)
    at Object.runServer [as func] (E:\front\source\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (E:\front\source\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:164:23)
    at Command.listener (E:\front\source\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (E:\front\source\node_modules\commander\index.js:651:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! listar@1.0.0 start: `react-native start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the listar@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-11-17T15_42_29_008Z-debug.log

**Comment by ydgkkang** [comment]
different way using ### yarn.

info Linking assets to ios project
info Linking assets to android project
success Assets have been successfully linked to your project
PS E:\front\source> yarn start
yarn run v1.19.0
$ react-native start
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (E:\front\source\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (E:\front\source\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:66:59)
    at getDefaultConfig (E:\front\source\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:82:20)
    at load (E:\front\source\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:118:25)
    at Object.runServer [as func] (E:\front\source\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (E:\front\source\node_modules\@react-native-community\cli\build\index.js:164:23)
    at Command.listener (E:\front\source\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (E:\front\source\node_modules\commander\index.js:651:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ydgkkang** [comment]
maybe node js -version 12.x (LTS) not working

**Comment by devswift2017** [comment]
You can try nodejs 12.10 install via package

**Comment by devswift2017** [comment]
You are done resolve this isssue ?

**Comment by ydgkkang** [comment]
Yes
Thank you to comment.
Node js 10.x running cool

2019년 11월 21일 (목) 오전 11:44, Dũng <notifications@github.com>님이 작성:

**Comment by ghost** [comment]
Welcome, Thanks for response
